---
# Determine how many "main" drives we have
- name: Get drive count
  shell: /bin/ls -1 /mnt | /usr/bin/wc -l
  register: driveCount
  changed_when: false

  # Setup fstab
- name: Setup mount for C drive
  become: true
  lineinfile:
    dest: /etc/fstab
    state: present
    regexp: '^C:\s+\/mnt\/c'
    line: 'C:  /mnt/c  drvfs  defaults,noatime,uid=1000,gid=1000,fmask=017,metadata,case=off  0  0'
    backup: yes

- name: Setup mount for D drive
  become: true
  lineinfile:
    dest: /etc/fstab
    state: present
    regexp: '^D:\s+\/mnt\/d'
    line: 'D:  /mnt/d  drvfs  defaults,noatime,uid=1000,gid=1000,fmask=117,metadata,case=off  0  0'
    backup: yes
  when: driveCount.stdout != '1'

- name: Copy wsl.conf
  become: true
  template:
    src: etc--wsl_conf.j2
    dest: /etc/wsl.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
