---
- name: Base setup
  hosts: localhost
  roles:
    - { role: upgrade, apt_upgrade_level: full}
    - base-packages
    - allow-sudo
    - ssh

- name: Main Setup
  hosts: localhost
  roles:
    - apt-configuration
