---
- name: Base setup
  hosts: localhost
  roles:
    - { role: upgrade, apt_upgrade_level: full}
    - base-packages
    - allow-sudo
    - ssh
    - apt-configuration

- name: Main Applications
  hosts: localhost
  vars:
    package_set: "Main Applications"
  vars_files:
    - vars/applications/base-packages.yml
    - vars/applications/dev-libraries.yml
    - vars/applications/emacs.yml
    - vars/applications/flatpak.yml
    - vars/applications/hub.yml
    - vars/applications/neovim.yml
    - vars/applications/rcm.yml
  roles:
    - install-applications

- name: Configurations
  hosts: localhost
  roles:
    - security
    - configure-alternatives
    - configure-wsl
