---
ppa_repositories:
    - "ppa:martin-frost/thoughtbot-rcm" # for rcm
    - "ppa:cpick/hub" # for hub
    - "ppa:alexlarsson/flatpak" # for flatpak
    - "ppa:git-core/ppa" # for updates to Git
    - "ppa:jonathonf/vim" # for updates to Vim
    - "ppa:kelleyk/emacs" # for updates to Emacs
    - "ppa:neovim-ppa/stable" # for Neovim
apt_packages:
# Hardware tools
    - hwdata
    - lsb-release
# Disk & Filesystem Tools
    - attr
# Apt tools
    - apt-transport-https
    - ca-certificates
    - unattended-upgrades
    - apt-listchanges
    - gdebi-core
# Monitoring & Networking Tools
    - htop
    - iotop
    - cpuid
    - cpustat
    - nmap
    - smbclient
    - sshfs
# Git & Subversion
    - git
    - git-doc
    - git-flow
    - git-extras
    - hub
# Install Zsh
    - zsh
    - zsh-doc
    - zsh-syntax-highlighting
    - zsh-antigen
# Compression
    - atool
    - unrar
    - arc
    - arj
    - bzip2
    - cpio
    - lzip
    - lzop
    - lzma
    - p7zip-full
    - rar
    - unace
    - unalz
    - xz-utils
    - zip
    - unzip
    - dtrx
# Common applications
    - moreutils
    - command-not-found
    - vifm
    - ranger
    - tmux
    - curl
    - wget
    - rsync
    - jq
    - tree
    - screenfetch
    - scrot
    - urlview
    - xsel
    - thefuck
# Editors
    - emacs26
    - exuberant-ctags
    - vim.nox
    - neovim
    - python-neovim
# Linters
    - shellcheck
    - gitlint
    - lacheck
    - libxml2-utils
    - yamllint
# Latex
    - texlive-full
    - pandoc

### Other stuff to install
# lab -> gitlab version of hub
# rg
